console.log("Suma de Dos numeros3+7 es: ");
console.log(3+7);
console.log("Resta de los numeros 13-7 es : ");
console.log(13-7);
console.log("expresion con parentesis (8*2-4)/3 es : ");
console.log(8*2-4)/3;
console.log("");
console.log("=>"+(13+7));
console.log("=>"+("13"+"7"));
console.log("=>"+("13"+7));
console.log("=>"+(+"13"+7));
console.log("=>"+(+"40"+"50"));
